// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BancoGrupoMatheusAPI.DAL;

namespace BancoGrupoMatheusAPI.Migrations
{
    [DbContext(typeof(DBContextBancoGrupoMatheus))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BancoGrupoMatheusAPI.Models.Contas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeroContaGenerated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TipoDeConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDeTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PinStoredHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Fatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PinStoredSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("contas");
                });

            modelBuilder.Entity("BancoGrupoMatheusAPI.Models.Transacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinoTransferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoTransferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaldoTransferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusTransferencia")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransferencia")
                        .HasColumnType("int");

                    b.Property<int>("Fatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalFatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenciaTransferencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
